# Generated by Django 4.2.18 on 2025-02-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='image',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='id',
        ),
        migrations.AddField(
            model_name='incident',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
